### ISSUE TITLE
API Integration tests: Users

### ISSUE THREAD

**Issue by AdrianKokot** [AdrianKokot/put-reunice-platform#143]
Add API Integration tests (jUnit - [see sample](https://github.com/AdrianKokot/put-reunice-platform/blob/main/backend/src/test/java/com/example/cms/page/PageControllerTest.java)) that cover User resource.

_Main administrator_ should be able to:
- View users list
- Create user of any type (main administrator, university administrator, university user)
- Edit any user
  - Changing password included
- Disable any user
- Enable any user
- Batch create users from file [not implemented]

_University administrators_ should be able to:
- View users list of his/her university
- Create a new user of type university admin or university user, assigned to the same university as the administrator
- Edit user of his/her university
  - Changing password included
- Delete user of his/her university
- Disable user of his/her university
- Enable user of his/her university

_University users_ should be able to:
- View users list of his/her university [needed for binding contact persons]

If the action is not listed to the specified role, it should be forbidden.

**Comment by AdrianKokot** [comment]
@BartoszDolata jak już znalazłeś błędy w formularzu edycji użytkownika, to może chcesz dorobić testy API do tego? :) Przykład jest w podlinkowanym pliku, nie ma co prawda na akcje typu POST/PUT/DELETE, ale myślę, że ogarniesz :) 
Przy akcjach POST/PUT jest walidacja CSRF, w teście możesz sobie go załadować za pomocą [tego](https://docs.spring.io/spring-security/reference/servlet/test/mockmvc/csrf.html)

**Comment by BartoszDolata** [comment]
Mogę spróbować podłubać :D
