### ISSUE TITLE
Propozycje zmian do usługi wysyłania maili

### ISSUE THREAD

**Issue by BartoszDolata** [AdrianKokot/put-reunice-platform#147]
- Wysyłanie chyba lepiej zrobić po wywołaniu repository.save() bo jeśli jest jakiś błąd walidacji (np. za długa nazwa użytkownika), to dopiero .save() to zwróci. W takim wypadku może pójść mail o zmianie hasła, a sama edycja się na przykład nie powiedzie.
- Nie wiem, czy nie lepiej, żeby treści maila były po angielsku lub żeby folder do szablonów był poza classpathem (tak jak np. folder uploads do obrazków), żeby w razie co można było zmienić zawartość szablonu bez rekompilacji aplikacji

**Comment by AdrianKokot** [comment]
Done
