### ISSUE TITLE
API Integration tests: Tickets

### ISSUE THREAD

**Issue by AdrianKokot** [AdrianKokot/put-reunice-platform#156]
TODO: transcribe requirements for tests from use cases

**Comment by AdrianKokot** [comment]
@WiktorSzymanski skoro sama funkcjonalność zapytań zrobiona, to może chcesz wypisać wszystkie use casey i napisać testy? :)

**Comment by WiktorSzymanski** [comment]
Mogę to zrobić, jeszcze tylko chce tam powywalać jakieś metody i endpointy ktore wydają się zbędne.

**Comment by AdrianKokot** [comment]
Też warto przetestować te rzeczy od użytkownika anonimowego
