### ISSUE TITLE
Status changed by whom

### ISSUE THREAD

**Issue by WiktorSzymanski** [AdrianKokot/put-reunice-platform#164]
Add to Ticket field who last updated it's status

**Comment by mudziok** [comment]
While we're at it we could also store requesters name as now we have to identify him on the ui as his email.
Simple `requesterName` in Ticket would do

**Comment by WiktorSzymanski** [comment]
A to źle że jest mailem? 
Czy wystarczy Id jako kto ostatni zmienił status?
I czy jak jest handled bo ktoś odpisał to też musi być przez kogo zmieniony? skoro w sumie to widać kto odpisał?

**Comment by AdrianKokot** [comment]
> A to źle że jest mailem?

w use cases nie kojarze żeby było coś o imieniu i nazwisku osoby pytającej więc chyba mail będzie git
