### ISSUE TITLE
🐞 Language switcher image cut

### ISSUE THREAD

**Issue by AdrianKokot** [AdrianKokot/put-reunice-platform#197]
![obraz](https://github.com/AdrianKokot/put-reunice-platform/assets/35179235/4952aaac-0e54-4067-865b-6be2fa2ed989)

Obrazek flagi jest lekko ucięty

**Comment by AdrianKokot** [comment]
@mudziok przy łączeniu fe <-> be z powiadomieniami możesz zerknąć
może lepiej przełączyć się na inputy z mniejszym paddingiem w top-barze?

**Comment by mudziok** [comment]
jasne spojrzę na to dzisiaj
