### ISSUE TITLE
Add FileResource integrity checks

### ISSUE THREAD

**Issue by AdrianKokot** [AdrianKokot/put-reunice-platform#247]
Aha no i w sumie to przydałoby się zrobić zabezpieczenia, że np. university user/university administrator może edytować lub usunąć plik tylko jeśli `principal.enrolledUniversities.contains(resource.author.enrolledUniversities)` czy jakoś tak, ale to już możesz osobno

_Originally posted by @AdrianKokot in https://github.com/AdrianKokot/put-reunice-platform/issues/243#issuecomment-1913522251_

**Comment by AdrianKokot** [comment]
@BartoszDolata ogarniesz?

**Comment by BartoszDolata** [comment]
No mogę, ale to na dziś musi być zrobione?

**Comment by AdrianKokot** [comment]
> No mogę, ale to na dziś musi być zrobione?

raczej nie
