### ISSUE TITLE
University filters not working on logged user

### ISSUE THREAD

**Issue by AdrianKokot** [AdrianKokot/put-reunice-platform#36]
Nie działa tak jak powinno, gdy użytkownik jest zalogowany to nie działa filtrowanie po `University.id` ani `Creator.id`, w dodatku `CompoundSpecification` jest jakieś dziwnie wielkie (masa `and` w wygenerowanym sqlu pomimo posiadania tylko 3 warunków).

To jest do rozpatrzenia i naprawy @WiktorSzymanski

_Originally posted by @AdrianKokot in https://github.com/AdrianKokot/put-reunice-platform/pull/33#discussion_r1304426757_

**Comment by WiktorSzymanski** [comment]
Ale chodzi w page-u aby filtrować po University.id i Creator.id? Jeśli tak to robiłem po primitywnych typach ( i może gdzieś jakiś enum ) więc tu jako ze jedno ma typ University a drugie User to po tym filtrowania nie ma.

**Comment by AdrianKokot** [comment]
Wiem, że robiłeś po prymitywach więc dodałem ręcznie filtrowanie po University.id oraz Creator.id bo do tabelki ma to sens. Ogólnie filtrowanie działa ale dla niezalogowanego użytkownika wtedy, bo przez  ten warunek, który zakomentowałem w PR dochodziło do bardzo dużej rozbudowy wynikowego SQLa, który sam sobie przeczył bo dochodziło do warunku w stylu page.hidden = true and page.hidden = false. Trzeba zrobić tak, że jeśli listę stron odpytuje zalogowany użytkownik to może sobie filtrować po University.Id, Creator.Id, Hidden, ale z wyjątkiem, że np. jeśli jestem university administrator i nie jestem przypisany do university o id 3, to jeśli dam filtr na univeristy_eq=3 to dostanę pustą listę
