### ISSUE TITLE
🐞 ActiveZone sidebar

### ISSUE THREAD

**Issue by AdrianKokot** [AdrianKokot/put-reunice-platform#67]
> This code is bugged - if you hover datalist inside the sidebar it closes the sidebar. Im pretty sure this is the issue of ActiveZone as the datalist is portalled somewhere else in the dom.

_Originally posted by @mudziok in https://github.com/AdrianKokot/put-reunice-platform/pull/66#issue-1888871763_

**Comment by mudziok** [comment]
Merged into searchbar feature branch
