### ISSUE TITLE
Rozbudowa schematu bazy danych o Contact request handler

### ISSUE THREAD

**Issue by WiktorSzymanski** [AdrianKokot/put-reunice-platform#89]
- [x] Schemat bazy danych dla CRH
 - [x] Schemat bazy danych dla ticketów
 - [x] Klasy tworzące tabele
 - [x] Dummy data
 - [x] Get endpoint zwracający tickety (main admin ma dostęp, inni użytkownicy tylko ich tickety)
 - [x] paginacja do ticketów

**Comment by AdrianKokot** [comment]
Done in #90
